### ISSUE TITLE
Upload demo

### ISSUE THREAD

**Issue by iilyak** [iilyak/couchdb-manifest#1]
![couchdb-manifest demo optimized](https://cloud.githubusercontent.com/assets/9804420/12464876/22bf872e-bf80-11e5-9fd3-5b23e0ca924d.gif)

[couchdb-manifest.tty.zip](https://github.com/iilyak/couchdb-manifest/files/98185/couchdb-manifest.tty.zip)

**Comment by kxepal** [comment]
This. Is. Awesome!
